# Generated by Django 6.0.3 on 2026-03-24 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_user_customer_public_id_customer_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Tu ID de Telegram para recibir notificaciones', max_length=50, null=True)),
                ('store_name', models.CharField(blank=True, help_text='Nombre comercial de tu tienda', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
