# Generated by Django 6.0.3 on 2026-03-25 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
